# core/events.py

TIME_REACHED         = "TIME_REACHED"
MORNING_WAKEUP       = "MORNING_WAKEUP"
BUTTON_PRESS         = "BUTTON_PRESS"
LIGHT_SENSOR_TRIGGER = "LIGHT_SENSOR_TRIGGER"
SYSTEM_BOOT          = "SYSTEM_BOOT"
DATA_COLLECTION      = "DATA_COLLECTION"
PRESENCE_DETECTED    = "PRESENCE_DETECTED"   # Motion-Sensor hat jemanden erkannt
TUTOR_START          = "TUTOR_START"          # Sprachtutor-Session beginnen