#!/usr/bin/env bash
# =============================================================================
# install_display_debug.sh
# -----------------------------------------------------------------------------
# Aktiviert den lightdm-Hook fuer display_debug.sh auf dem Pi.
#
# WAS DAS MACHT:
# Schreibt eine lightdm-Conf-Snippet-Datei nach
# /etc/lightdm/lightdm.conf.d/60-zentrale-display-debug.conf, die bei jedem
# lightdm-Start den display-setup-script-Hook auf display_debug.sh setzt.
# Damit wird bei JEDEM X-Start automatisch ein Snapshot-Triple (T+0/T+5/T+15s)
# nach ~sasha/zentrale-display-debug.log geschrieben.
#
# AUFRUF (auf dem Pi, einmalig nach git pull):
#   sudo bash /opt/zentrale/scripts/install_display_debug.sh
#
# DEINSTALLATION:
#   sudo rm /etc/lightdm/lightdm.conf.d/60-zentrale-display-debug.conf
#
# Idempotent: kann beliebig oft ausgefuehrt werden, ueberschreibt das
# Snippet jedes Mal mit dem aktuellen Pfad.
# =============================================================================

set -euo pipefail

# Pfad zum eigentlichen Debug-Skript. Wir benutzen einen absoluten Pfad
# im lightdm-Hook (relative funktionieren da nicht), darum hier hart
# gegen den Standard-Deploy-Pfad /opt/zentrale.
DEBUG_SCRIPT="/opt/zentrale/scripts/display_debug.sh"
HOOK_CONF="/etc/lightdm/lightdm.conf.d/60-zentrale-display-debug.conf"

# Sanity-Check: Debug-Skript muss ausfuehrbar existieren, sonst wuerde
# der lightdm-Hook stumm scheitern und wir wuerden uns wundern warum
# keine Snapshots kommen.
if [ ! -x "$DEBUG_SCRIPT" ]; then
    echo "FEHLER: $DEBUG_SCRIPT existiert nicht oder ist nicht ausfuehrbar."
    echo "Tipp: chmod +x $DEBUG_SCRIPT"
    exit 1
fi

# Root-Check. lightdm.conf.d/ gehoert root, ohne sudo geht nichts.
if [ "$(id -u)" != "0" ]; then
    echo "FEHLER: bitte als root aufrufen (sudo bash $0)"
    exit 1
fi

# Snippet schreiben. [Seat:*] gilt fuer alle Sitze - der Pi hat nur einen.
# display-setup-script laeuft als root NACH Xorg-Start und VOR Greeter/
# Auto-Login. Perfekter Zeitpunkt fuer T+0: X laeuft, Mode ist gerade
# gesetzt, noch keine Session druebergebeamt.
cat > "$HOOK_CONF" <<EOF
# Auto-generated by install_display_debug.sh - dont edit manually.
# Triggers ZENTRALE display_debug.sh on every X start.
[Seat:*]
display-setup-script=$DEBUG_SCRIPT autostart
EOF

echo "Hook installiert: $HOOK_CONF"
echo "Inhalt:"
sed 's/^/  /' "$HOOK_CONF"
echo
echo "Aktiv beim naechsten lightdm-Start:"
echo "  sudo systemctl start lightdm"
echo
echo "Log liegt unter: /home/sasha/zentrale-display-debug.log"
echo "Live verfolgen:  tail -F /home/sasha/zentrale-display-debug.log"
