-- zentrale_theme.highlights — Rollen einer Palette → nvim-Highlight-Gruppen.
--
-- EINE Zuordnung für BEIDE Paletten (cyber/paper): die Paletten liefern nur
-- Farben unter gleichnamigen Rollen (siehe palettes.lua), die Struktur steht
-- hier. So kann eine Palette nicht Gruppen vergessen, die die andere hat.

local M = {}

--- Baut die komplette Gruppen-Tabelle für eine Palette.
--- @param p table Palette aus palettes.lua
--- @return table<string, table> group → nvim_set_hl-Attribute
function M.build(p)
  local it = p.comment_italic and true or nil
  local g = {
    -- ── Grundflächen ────────────────────────────────────────────────────
    Normal        = { fg = p.fg, bg = p.bg },
    NormalNC      = { fg = p.fg, bg = p.bg },
    NormalFloat   = { fg = p.fg, bg = p.bg_alt },
    FloatBorder   = { fg = p.border, bg = p.bg_alt },
    FloatTitle    = { fg = p.title, bg = p.bg_alt, bold = true },
    Cursor        = { fg = p.bg, bg = p.accent },
    lCursor       = { fg = p.bg, bg = p.accent },
    TermCursor    = { fg = p.bg, bg = p.accent },
    CursorLine    = { bg = p.bg_dim },
    CursorColumn  = { bg = p.bg_dim },
    ColorColumn   = { bg = p.bg_dim },
    LineNr        = { fg = p.line_nr, bg = p.bg },
    LineNrAbove   = { fg = p.line_nr, bg = p.bg },
    LineNrBelow   = { fg = p.line_nr, bg = p.bg },
    CursorLineNr  = { fg = p.line_nr_cur, bg = p.bg_dim, bold = true },
    SignColumn    = { fg = p.line_nr, bg = p.bg },
    FoldColumn    = { fg = p.line_nr, bg = p.bg },
    Folded        = { fg = p.fg_faint, bg = p.bg_alt },
    Visual        = { bg = p.bg_sel },
    VisualNOS     = { bg = p.bg_sel },
    MatchParen    = { fg = p.accent, bg = p.bg_match, bold = true },
    Whitespace    = { fg = p.line_nr },
    NonText       = { fg = p.line_nr },
    EndOfBuffer   = { fg = p.line_nr },
    SpecialKey    = { fg = p.special },
    Conceal       = { fg = p.fg_dim },
    Directory     = { fg = p.accent },
    Title         = { fg = p.title, bold = true },
    Question      = { fg = p.ok },
    MoreMsg       = { fg = p.ok },
    ModeMsg       = { fg = p.fg_dim, bold = true },
    MsgArea       = { fg = p.fg, bg = p.bg },
    MsgSeparator  = { fg = p.border, bg = p.bg },
    ErrorMsg      = { fg = p.error, bold = true },
    WarningMsg    = { fg = p.warn },

    -- ── Suche ───────────────────────────────────────────────────────────
    Search        = { fg = p.search_fg,    bg = p.search_bg },
    IncSearch     = { fg = p.cursearch_fg, bg = p.cursearch_bg },
    CurSearch     = { fg = p.cursearch_fg, bg = p.cursearch_bg },
    Substitute    = { fg = p.search_fg,    bg = p.search_bg },
    QuickFixLine  = { bg = p.bg_sel },

    -- ── Fenster-Chrom ───────────────────────────────────────────────────
    StatusLine    = { fg = p.status_fg,    bg = p.status_bg, bold = true },
    StatusLineNC  = { fg = p.status_nc_fg, bg = p.status_nc_bg },
    WinBar        = { fg = p.status_fg,    bg = p.bg, bold = true },
    WinBarNC      = { fg = p.status_nc_fg, bg = p.bg },
    WinSeparator  = { fg = p.border, bg = p.bg },
    VertSplit     = { fg = p.border, bg = p.bg },
    TabLine       = { fg = p.status_nc_fg, bg = p.status_nc_bg },
    TabLineSel    = { fg = p.status_fg,    bg = p.bg, bold = true },
    TabLineFill   = { bg = p.status_nc_bg },
    Pmenu         = { fg = p.fg,       bg = p.bg_alt },
    PmenuSel      = { fg = p.pmenu_sel_fg, bg = p.pmenu_sel_bg, bold = true },
    PmenuKind     = { fg = p.type,     bg = p.bg_alt },
    PmenuKindSel  = { fg = p.type,     bg = p.pmenu_sel_bg },
    PmenuExtra    = { fg = p.fg_faint, bg = p.bg_alt },
    PmenuExtraSel = { fg = p.fg_dim,   bg = p.pmenu_sel_bg },
    PmenuSbar     = { bg = p.bg_alt },
    PmenuThumb    = { bg = p.border },
    WildMenu      = { fg = p.pmenu_sel_fg, bg = p.pmenu_sel_bg },

    -- ── Syntax (klassische Gruppen; Treesitter linkt weiter unten) ───────
    Comment       = { fg = p.fg_faint, italic = it },
    Constant      = { fg = p.constant },
    String        = { fg = p.string },
    Character     = { fg = p.string },
    Number        = { fg = p.number },
    Float         = { fg = p.number },
    Boolean       = { fg = p.number },
    Identifier    = { fg = p.fg },
    Function      = { fg = p.accent },
    Statement     = { fg = p.keyword },
    Conditional   = { fg = p.keyword },
    Repeat        = { fg = p.keyword },
    Label         = { fg = p.keyword },
    Operator      = { fg = p.fg_dim },
    Keyword       = { fg = p.keyword },
    Exception     = { fg = p.error },
    PreProc       = { fg = p.constant },
    Include       = { fg = p.keyword },
    Define        = { fg = p.constant },
    Macro         = { fg = p.constant },
    PreCondit     = { fg = p.constant },
    Type          = { fg = p.type },
    StorageClass  = { fg = p.type },
    Structure     = { fg = p.type },
    Typedef       = { fg = p.type },
    Special       = { fg = p.special },
    SpecialChar   = { fg = p.special },
    Tag           = { fg = p.property },
    Delimiter     = { fg = p.fg_dim },
    SpecialComment= { fg = p.fg_dim, italic = it },
    Debug         = { fg = p.warn },
    Underlined    = { fg = p.accent, underline = true },
    Ignore        = { fg = p.fg_faint },
    Error         = { fg = p.error, bold = true },
    Todo          = { fg = p.todo_fg, bg = p.todo_bg, bold = true },

    -- ── Spell / Diff ────────────────────────────────────────────────────
    SpellBad      = { sp = p.error, undercurl = true },
    SpellCap      = { sp = p.warn,  undercurl = true },
    SpellLocal    = { sp = p.info,  undercurl = true },
    SpellRare     = { sp = p.hint,  undercurl = true },
    DiffAdd       = { bg = p.diff_add },
    DiffDelete    = { fg = p.error, bg = p.diff_del },
    DiffChange    = { bg = p.diff_chg },
    DiffText      = { bg = p.diff_txt, bold = true },
    Added         = { fg = p.ok },
    Changed       = { fg = p.info },
    Removed       = { fg = p.error },

    -- ── Diagnostics ─────────────────────────────────────────────────────
    DiagnosticError = { fg = p.error },
    DiagnosticWarn  = { fg = p.warn },
    DiagnosticInfo  = { fg = p.info },
    DiagnosticHint  = { fg = p.hint },
    DiagnosticOk    = { fg = p.ok },
    DiagnosticUnderlineError = { sp = p.error, undercurl = true },
    DiagnosticUnderlineWarn  = { sp = p.warn,  undercurl = true },
    DiagnosticUnderlineInfo  = { sp = p.info,  undercurl = true },
    DiagnosticUnderlineHint  = { sp = p.hint,  undercurl = true },
    DiagnosticUnderlineOk    = { sp = p.ok,    undercurl = true },
    DiagnosticVirtualTextError = { fg = p.error, italic = true },
    DiagnosticVirtualTextWarn  = { fg = p.warn,  italic = true },
    DiagnosticVirtualTextInfo  = { fg = p.info,  italic = true },
    DiagnosticVirtualTextHint  = { fg = p.hint,  italic = true },
    DiagnosticVirtualTextOk    = { fg = p.ok,    italic = true },

    -- ── Treesitter-Captures (nur wo sie NICHT schon passend erben) ───────
    ["@variable"]           = { fg = p.fg },
    ["@variable.builtin"]   = { fg = p.constant, italic = true },
    ["@variable.parameter"] = { fg = p.fg_dim },
    ["@variable.member"]    = { fg = p.property },
    ["@property"]           = { fg = p.property },
    ["@field"]              = { fg = p.property },
    ["@module"]             = { fg = p.type },
    ["@constant"]           = { fg = p.constant },
    ["@constant.builtin"]   = { fg = p.constant, italic = true },
    ["@function"]           = { fg = p.accent },
    ["@function.builtin"]   = { fg = p.accent, italic = true },
    ["@function.call"]      = { fg = p.accent },
    ["@function.method"]    = { fg = p.accent },
    ["@constructor"]        = { fg = p.type },
    ["@keyword"]            = { fg = p.keyword },
    ["@keyword.return"]     = { fg = p.keyword, bold = true },
    ["@type"]               = { fg = p.type },
    ["@type.builtin"]       = { fg = p.type, italic = true },
    ["@attribute"]          = { fg = p.special },
    ["@string"]             = { fg = p.string },
    ["@string.escape"]      = { fg = p.special },
    ["@string.special"]     = { fg = p.special },
    ["@operator"]           = { fg = p.fg_dim },
    ["@punctuation.delimiter"] = { fg = p.fg_dim },
    ["@punctuation.bracket"]   = { fg = p.fg_dim },
    ["@punctuation.special"]   = { fg = p.special },
    ["@comment"]            = { fg = p.fg_faint, italic = it },
    ["@comment.error"]      = { fg = p.todo_fg, bg = p.error, bold = true },
    ["@comment.warning"]    = { fg = p.bg, bg = p.warn, bold = true },
    ["@comment.todo"]       = { fg = p.todo_fg, bg = p.todo_bg, bold = true },
    ["@comment.note"]       = { fg = p.bg, bg = p.info, bold = true },
    ["@tag"]                = { fg = p.keyword },
    ["@tag.attribute"]      = { fg = p.property },
    ["@tag.delimiter"]      = { fg = p.fg_dim },
    ["@markup.heading"]     = { fg = p.title, bold = true },
    ["@markup.strong"]      = { bold = true },
    ["@markup.italic"]      = { italic = true },
    ["@markup.link"]        = { fg = p.accent, underline = true },
    ["@markup.link.url"]    = { fg = p.info, underline = true },
    ["@markup.raw"]         = { fg = p.string },
    ["@markup.list"]        = { fg = p.special },
    ["@markup.quote"]       = { fg = p.fg_dim, italic = true },
    ["@diff.plus"]          = { fg = p.ok },
    ["@diff.minus"]         = { fg = p.error },
    ["@diff.delta"]         = { fg = p.info },
  }
  return g
end

return M
